### ISSUE TITLE
[Question] Is it possible to update existing TOML file?

### ISSUE THREAD

**Issue by levicki** [ToruNiina/toml11#122]
Let me first thank you for this great and easy to use library. So far I have been using it successfully to read values from TOML files.

I have checked all the examples in the README, but I could not find an example of updating an existing TOML file.

Basically, I need to parse the whole file, change one or more values, and then save the whole thing back, preferrably without losing comments and whitespace.

What would be the best way to do that using your library?

**Comment by ToruNiina** [comment]
You can modify toml::value unless it is marked as `const`.
By specifying `toml::preserve_comments`, the comments are preserved and written in the file.

Even if you substitute some value, the comments are kept. If you want to modify comments, you can pass a list of comment lines, `std::vector<std::string>`, as a second argumnet of the constructor of `toml::value`.

With the following toml file,

```toml
# example.toml

title = "example"
foo = 42 # will be overwritten

# no `qux` there

[math]
# approximation
pi = 3.1416
```

This C++ code ...

```cpp
auto file = toml::parse<toml::preserve_comments>("example.toml");
file["foo"] = "bar";
file["qux"] = toml::value(42, {"comment on qux"});
std::cout << std::setw(80) << file << std::endl;
```

outputs the following.

```toml
# example.toml

qux = 42
# will be overwritten
foo = "bar"
title = "example"
[math]
# approximation
pi = 3.1416
```

But sorry, currently there is no way to preserve the indentation. It formats toml file (don't forget `std::setw`), but it does not use indentation.
