### ISSUE TITLE
Program crashes when last element is 0

### ISSUE THREAD

**Issue by s3pt3mb3r** [ToruNiina/toml11#128]
I found a bug that causes crash when the last element of toml is 0.

i wrote a code to read from toml file.
```cpp
void Read(const std::string& filename) {
    auto data = toml::parse(filename);
    auto tests = toml::find<std::vector<toml::table>>(config, "test");
    for (toml::table& test : tests) {
        std::cout << test["name"] << std::endl;
    }
}
```

and when the target toml file is like this below, it's gonna work fine.
```toml
[[test]]
name = "note"

[[test]]
name = "pen"
```

but when it comes to this, program crashes.
```toml
[[test]]
name = "note"

[[test]]
name = "pen"
a = 0
```
