### ISSUE TITLE
Doesn't correctly parse nan or inf.

### ISSUE THREAD

**Issue by tfiner** [ToruNiina/toml11#49]
The special values (taken from the TOML github page), are not parsed correctly:

> infinity
> sf1 = inf # positive infinity
> sf2 = +inf # positive infinity
> sf3 = -inf # negative infinity
> 
> not a number
> sf4 = nan # actual sNaN/qNaN encoding is implementation specific
> sf5 = +nan # same as nan
> sf6 = -nan # valid, actual encoding is implementation specific

**Comment by ToruNiina** [comment]
Thank you for telling me this, but I couldn't reproduce that.
Do you have any information to reproduce it? Like, what compiler did you use, which version of toml11 fails, and what kind of behavior did you observe (e.g. throwing `syntax_error`)?

Actually, those values are checked in the unit test ([tests/test_parse_floating.cpp#L107-L158](https://github.com/ToruNiina/toml11/blob/master/tests/test_parse_floating.cpp#L107-L158)) and it [succeeds on CI](https://travis-ci.org/ToruNiina/toml11/builds/508695362?utm_source=github_status&utm_medium=notification).

Also, I've tested the following code on my laptop
```cpp
#include "toml.hpp"
#include <iostream>
#include <cmath>
#include <cassert>

int main()
{
    const auto data = toml::parse("special_float.toml");

    std::cout << toml::get<double>(data.at("sf1")) << std::endl;
    std::cout << toml::get<double>(data.at("sf2")) << std::endl;
    std::cout << toml::get<double>(data.at("sf3")) << std::endl;

    assert(std::isinf(toml::get<double>(data.at("sf1"))));
    assert(std::isinf(toml::get<double>(data.at("sf2"))));
    assert(std::isinf(toml::get<double>(data.at("sf3"))));

    std::cout << toml::get<double>(data.at("sf4")) << std::endl;
    std::cout << toml::get<double>(data.at("sf5")) << std::endl;
    std::cout << toml::get<double>(data.at("sf6")) << std::endl;

    assert(std::isnan(toml::get<double>(data.at("sf4"))));
    assert(std::isnan(toml::get<double>(data.at("sf5"))));
    assert(std::isnan(toml::get<double>(data.at("sf6"))));

    std::cerr << data;

    return 0;
}
```
with the following toml file
```toml
# infinity
sf1 = inf # positive infinity
sf2 = +inf # positive infinity
sf3 = -inf # negative infinity

# not a number
sf4 = nan # actual sNaN/qNaN encoding is implementation specific
sf5 = +nan # same as nan
sf6 = -nan # valid, actual encoding is implementation specific
```
and it works with the following output.
```console
inf
inf
-inf
nan
nan
nan
```
